### PR TITLE
Created_quote_component

### PR DESCRIPTION
**Pull request by FarwaMuhibZada**
# Random Quote Machine 🔁

## Description 📜

The Random Quote Machine is a simple web application that displays random quotes along with their authors. Users can fetch new quotes and share them on Twitter. This project is built using React  to fulfill the requirements of the freeCodeCamp Front End Development Libraries projects.

## Features 🎉

- Display a random quote and author on page load
- Fetch a new quote on button click
- Share the current quote on Twitter
- Responsive design 

## User Stories 👧

1. I can see a wrapper element with a corresponding `id="quote-box"`.
2. Within `#quote-box`, I can see an element with a corresponding `id="text"`.
3. Within `#quote-box`, I can see an element with a corresponding `id="author"`.
4. Within `#quote-box`, I can see a clickable element with a corresponding `id="new-quote"`.
5. Within `#quote-box`, I can see a clickable `a` element with a corresponding `id="tweet-quote"`.
6. On first load, my quote machine displays a random quote in the element with `id="text"`.
7. On first load, my quote machine displays the random quote's author in the element with `id="author"`.
8. When the `#new-quote` button is clicked, my quote machine should fetch a new quote and display it in the `#text` element.
## Demo 📸
Capture
deployment link: https://random-quote-machine-sg8ug70th-farwamuhibzadas-projects.vercel.app/

### CODE REVIEW

**Comment by MasomRezaie** [comment]
@FarwaMuhibZada Well done Farwa jan. As i review your project, it is great and does not have any mistake. Your Readme file is great. Your coding is clean, and does not have linters error.

**Comment by FarwaMuhibZada** [comment]
> @FarwaMuhibZada Well done Farwa jan. As i review your project, it is great and does not have any mistake. Your Readme file is great. Your coding is clean, and does not have linters error.

@MasomRezaie thanks for your reviewing  and feedback .

**Comment by ahzamir** [comment]
@FarwaMuhibZada 

Hey Farwa, Your deployment with Vercel has no access for public check:
image

And with the netlify it prints an empty page please check and solve the issue.

**Comment by FarwaMuhibZada** [comment]
> @FarwaMuhibZada
> 
> Hey Farwa, Your deployment with Vercel has no access for public check: image
> 
> And with the netlify it prints an empty page please check and solve the issue.

@ahzamir hello sir hope you are doing well there was problem on deployment .  I have solved it  you can check now  on both netify and vercel here are the links.
https://random-quote-machine-sg8ug70th-farwamuhibzadas-projects.vercel.app/
https://random-qoute-machine-farwamuhibzada.netlify.app/

**Review by ahzamir — APPROVED** [review]
### Hi @FarwaMuhibZada 🙋‍♀️,

> Excellent work! 💯 You have done a great job implementing all the project requirements. 🥳 Your feature is complete! Congratulations!!!🎊

- **[REQUIRED]** Share your project on this [GROUP](https://www.facebook.com/groups/kick-startdev), add a simple Proud Moment text and a screenshot of your project then besides that add your project link at the end of the text as a GitHub Source code reference and post.

- Share your Project on your LinkedIn account and add a proud moment text with a screenshot.

- Well Done great design Implemented. 🎯🎉👍
image

# Status: Approved ✅
There is nothing to say other than to merge your branch. 🎉🎯✅👍😊🥳

WinkThumbsUpGIF


 ## Highlights 🌞

🎉 Great Design Implemented 
✔️ Created a professional Repo (You created a repository with your project name)
✔️ Correct use of Gitflow (You created the development branch and made it your default branch, then created and committed your work on your feature branch)
✔️ Commit messages are meaningful
✔️ Setup the linters correctly (You added the correct linters config into your project according to the language you used on your code)
✔️ No linter errors (All linters checks have been passed 🟢)
✔️ You have followed the Random Quote Machine project task and committed using the command line
✔️ Created the pull request (From your feature branch to the development branch you created a pull request and submitted the pull request link for review)
✔️ Good PR description (You added a meaningful description to your PR about your work and the features you added on this pull request)
✔️Your code is clean
✔️Your repo has a professional README.md file
✔️ Your partner has reviewed your repo
✔️Your design is responsive

**Cheers 🥂 and Happy coding!!! 👯 Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Remember to tag me @ahzamir in your question so I can receive the notification.**

**Pull request merged**
